before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
    - darwin
    - windows
    - linux
  goarch:
    - amd64
  ldflags: -X github.com/jaxxstorm/ploy/pkg/version.Version={{.Version}}
  binary: ploy
  main: ./cmd/ploy/main.go
archives:
- name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  skip: true
release:
  prerelease: auto
brews:
  - 
    name: ploy
    tap:
      owner: jaxxstorm
      name: homebrew-tap
    commit_author:
      name: GitHub Actions
      email: bot@leebriggs.co.uk
    folder: Formula
    homepage: "https://leebriggs.co.uk"
    description: "Quickly install applications to Kubernetes with Pulumi"
