name: release
on:
  push:
    tags: [ v*.*.** ] # only a valid semver tag

jobs:    
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow clone
        run: git fetch --prune --unshallow
      - name: Install Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.x'
      - name: Goreleaser publish
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.145.0
          args: release --rm-dist
        env:
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
